export const SET_LOCALE = "SET_LOCALE";
export const CHANGE_THEME = "CHANGE_THEME";
export const SET_SESSION_ID = "SET_SESSION_ID";
export const SET_ALL_TORRENTS = "SET_ALL_TORRENTS";
export const SET_SESSION = "SET_SESSION";
export const TOGGLE_MENUOPEN = "TOGGLE_MENUOPEN";

// Add Torrent
export const TOGGLE_ADD_TORRENT_DIALOG = "TOGGLE_ADD_TORRENT_DIALOG";
