export const SET_LOCALE = "SET_LOCALE";
export const CHANGE_THEME = "CHANGE_THEME";
export const SET_SESSION_ID = "SET_SESSION_ID";
export const SET_TORRENTS = "SET_TORRENTS";
export const SET_SESSION = "SET_SESSION";
export const SET_SESSION_STATS = "SET_SESSION_STATS";
export const TOGGLE_MENUOPEN = "TOGGLE_MENUOPEN";
export const SET_SELECTED_IDS = "SET_SELECTED_IDS";

// Add Torrent
export const TOGGLE_ADD_TORRENT_DIALOG = "TOGGLE_ADD_TORRENT_DIALOG";

export const SET_MESSAGE_BAR = "SET_MESSAGE_BAR";
