name: Deploy To GCP
# on:
#   push:
#     branches:
#       - master
on: [push]
jobs:
  build-and-deploy:
    name: Deploy
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: CultureHQ/actions-yarn@master
        with:
          args: install
      - name: Build
        uses: CultureHQ/actions-yarn@master
        with:
          args: build
        env:
          REACT_APP_MUIX_LICENSE_KEY: ${{ secrets.REACT_APP_MUIX_LICENSE_KEY }}
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "build/*"
          target: "/mnt/disks/disk1/transmission/transmission-client"
          debug: true
