name: Deploy preview environment
on:
  release:
    types: [prereleased]
jobs:
  build-and-deploy:
    name: Deploy
    environment: demo
    runs-on: ubuntu-latest
    steps:
      - uses: robinraju/release-downloader@v1.1
        with:
          repository: "zj9495/transmission-client"
          tag: "pre-release"
          fileName: "build.zip"
      - name: Unzip
        run: unzip build.zip -d ./build
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PREVIEW_HOST }}
          username: ${{ secrets.PREVIEW_SSH_USER }}
          port: ${{ secrets.PREVIEW_SSH_PORT }}
          key: ${{ secrets.PREVIEW_SSH_KEY }}
          source: "build/*"
          target: ${{ secrets.PREVIEW_FILE_PATH }}
          strip_components: 1
