name: Deploy preview environment
on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
jobs:
  build-and-deploy:
    name: Deploy
    environment: demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: appleboy/scp-action@master
        with:
          host: frp.zj9495.com
          username: ubuntu
          port: 22
          key: ${{ secrets.DEPLOY_PREVIEW_SSH_KEY }}
          source: ".github/*"
          target: "/home/ubuntu/transmission-client"
          strip_components: 1
