name: Deploy preview environment
on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
jobs:
  build-and-deploy:
    name: Deploy
    environment: demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: nogsantos/scp-deploy@master
        with:
          host: frp.zj9495.com
          user: ubuntu
          port: 22
          key: ${{ secrets.DEPLOY_PREVIEW_SSH_KEY }}
          src: ".github/*"
          remote: "/home/ubuntu/transmission-client/"
