name: Pre release

on:
  push:
    branches:
      - master
    
env:
  TZ: Asia/Shanghai
  REACT_APP_MUIX_LICENSE_KEY: ${{ secrets.REACT_APP_MUIX_LICENSE_KEY }}

jobs:
  pre-release:
    name: Pre Release
    environment: stage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install
      - run: yarn build
      
      - name: Zip
        run: cd build && zip -r ../build.zip * && tar -zcvf ../build.tar.gz *

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.ACCESS_TOKEN }}
          automatic_release_tag: pre-release
          prerelease: true
          title: Development Build
          files: |
            LICENSE
            build.zip
            build.tar.gz
