name: Pre-release

on: [push]
# on:
#   push:
#     branches:
#       - master

jobs:
  pre-release:
    name: Pre Release
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

      - name: Install
        uses: CultureHQ/actions-yarn@master
        with:
          args: install
      - name: Build
        uses: CultureHQ/actions-yarn@master
        with:
          args: build
        env:
          REACT_APP_MUIX_LICENSE_KEY: ${{ secrets.REACT_APP_MUIX_LICENSE_KEY }}
      - name: Zip
        run: zip -r build.zip build/*

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          files: |
            LICENSE
            build.zip
