name: Tagged release

on:
  push:
    tags:
      - v*
    
env:
  TZ: Asia/Shanghai

jobs:
  tagged-release:
    name: Tagged release
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: 16
        env:
          REACT_APP_MUIX_LICENSE_KEY: ${{ secrets.REACT_APP_MUIX_LICENSE_KEY }}
      - run: yarn install
      - run: yarn build
      
      - name: Zip
        run: cd build && zip -r ../build.zip * && tar -zcvf ../build.tar.gz *

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            LICENSE
            build.zip
            build.tar.gz
