name: Sync To Gitee

on:
  push:
    branches: [master]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACTIONS_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:zj9495/transmission-client.git"
          destination-repo: "git@gitee.com:zj9495/transmission-client.git"